### ISSUE TITLE
Whitney gives both items again

### ISSUE THREAD

**Issue by choatix** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#10]
If you have full bag space upon defeating Whitney, she will give you the 'Plain Badge' followed by her 'TM'. However, if the first item fits in the bag fine, and the second does not, when you talk again again, you are given the first item again, and this is infinitely repeatable.

**Comment by erudnick-cohen** [comment]
This is a bug in speedchoice and has been reported to dabomstew, who maintains speedchoice.

**Comment by choatix** [comment]
Issue was fixed upstream in latest speedchoice release.
