### ISSUE TITLE
Johto Mode doesn't seem to work

### ISSUE THREAD

**Issue by pokemonfan1937** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#11]
Attempting to randomize using Johto Only mode results in this error:

Traceback (most recent call last): File "RunGUI.py", line 91, in runRandomizer File "RunCustomRandomizationAssumedFill.py", line 26, in randomizeRom TypeError: 'NoneType' object is not subscriptable

**Comment by erudnick-cohen** [comment]
Yup, looks like it. Probably got broken by a change made in the last few updates, thanks for reporting this. This will most likely get fixed when the next version of the item randomizer comes out.

**Comment by Trencha** [comment]
I've just come across this same issue using some customised randomiser settings. Upon investigation, it seems to be caused by an extra line that's been accidentally added to the ForceEarlyBike modifier.

**Comment by erudnick-cohen** [comment]
This bug is fixed as of the most recent randomizer release (V5)
