### ISSUE TITLE
Item Location

### ISSUE THREAD

**Issue by naboknight** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#15]
Is it possible to put an item's location on a board?
Example: "StormBadge is in Rainbow Wing Gift" or "Rainbow Wing Gift have an important item"
the map would also help: "StormBadge is in TinTower1F" or "TinTower1F have a...

I would like to implement this to decrease seed time in randomizer. I use my own version of speedchoice 7.2, where Mt.Silver opens with 12 bagdes, but the position of the cards always slow the game down.

If you can't implement it in the randomizer, can you tell me how it would be possible to do it in the rom?

**Comment by erudnick-cohen** [comment]
Randomizer now supports changing the number of badges needed and choatix is currently working on hints. Closing this commit as everything discussed is either now already done, or will done in the future.
