### ISSUE TITLE
Randomizer gets stuck despite feasible placements in a plando file

### ISSUE THREAD

**Issue by samfin** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#28]
When trying to create a randomized rom using the Extreme settings using a Plando file, the randomizer can get stuck in an infinite loop. The check at [RandomizeItemsBadgesAssumedFill.py#L295](https://github.com/erudnick-cohen/Pokemon-Crystal-Item-Randomizer/blob/master/RandomizeItemsBadgesAssumedFill.py#L295) incorrectly thinks that the item is in allDepsList and thus is a dependency for that location. 

As a result, the randomizer places the items somewhere else, then notices later that some items are not in the plando placements and tries again. The loop repeats infinitely. 

Here is an example Plando file which causes the stuck behavior: [example_SPOILER.txt](https://github.com/erudnick-cohen/Pokemon-Crystal-Item-Randomizer/files/7592144/example_SPOILER.txt).

To repro:
- Open the randomizer and load any Crystal ROM.
- Use Extreme.yml with Select Logic Settings.
- Use the file linked above for Load Plando File.

**Comment by erudnick-cohen** [comment]
fixed as of version 6 with new modifier
