### ISSUE TITLE
Randomizer will not open

### ISSUE THREAD

**Issue by vipertrek79** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#34]
Hi, I recently had to reinstall my OS and after re downloading this and trying to run the .exe it flashes a cmd prompt style window for a second and then nothing happens. I have python, and java and I'm not sure what all else I need or what could be the problem. Thanks :)

**Comment by erudnick-cohen** [comment]
which operating system did this occur on?

**Comment by vipertrek79** [comment]
Windows 10. turns out i didnt have java 14+ (no documentation of that is listed here, only in the bingo discord which is kinda weird) All works now :shrug:

**Comment by The-TeePunk** [comment]
I'd like to follow up on this. Win 10, Python 3 installed and Java 17 installed. Still only get a command-style screen for a split second, then it closes and does nothing. Any further ideas?
