### ISSUE TITLE
The .EXE version doesn't work for me

### ISSUE THREAD

**Issue by c-a0** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#38]
When I double-click Pokemon Crystal Item Randomizer.exe on Windows 10, the only thing that happens is that a command prompt box shows up for a split second and then closes. If I try to run it from the command line, I get this error message:
```
Traceback (most recent call last):
  File "RunGUI.py", line 4, in <module>
  File "c:\users\eliot\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "RandomizerGUI.py", line 10, in <module>
ImportError: DLL load failed: The specified module could not be found.
[10636] Failed to execute script RunGUI
```
And that's it. Note that my name isn't eliot and my computer doesn't have user named eliot, so I don't know why it's looking for a file in a folder called eliot. I've tried this on two different computers and the same thing happened on both. I also tried a few different releases of the program - same thing happened.

Somehow I got the program to run once. I tried to randomize a ROM with it, and while it did spit out a SPOILERS.txt file with a list of randomized item locations, the items in the actual output ROM weren't randomized. I used a Crystal V1.1 ROM that was patched with crystal-speedchoice7p31.ips and then randomized with UPR-v7p3-compat.jar (which I had to run from a Linux computer because the included UPR-Crystal-Speedchoice-7.31Compatible.exe file just displays the message "This application requires a Java Runtime Environment 14" when run in Windows, even after I installed Java). The speedchoice patch and UPR both worked fine.

**Comment by erudnick-cohen** [comment]
What anti-virus is installed on your machine? Its possible that could be interfering with something, they have been known to complain about the exe we distribute (or more generally, exes built using pyinstaller). To confirm, you are running the exe by downloading the zipped folder in releases and then clicking on the exe (you aren't doing any extra steps like moving something out of the folder), correct? This is a very strange set of errors that has not been reported before with the exe. If you want a potential workaround for this, if you install python and then install the PyYaml and PyQT packages, running the file "RunGUI.py" with python should allow you to run the randomizer. Also with regards to the java issue, what version of java do you have installed?

**Comment by c-a0** [comment]
I don't have any antivirus installed on either computer. 
Yes, I'm running the .exe exactly as you described. 
I'll try the Python workaround later and post another comment saying if it worked or not.

When the "Runtime Environment 14" error message comes up, closing the error message opens up a browser window with a website where you can download Java. I just downloaded that and installed it, but it didn't make any difference. That's okay though - I can just run it on Linux. The main reason I wanted to post about the error is that I tried to Google it and nothing relevant came up, so I just wanted to post something that others can find if they Google the error.

**Comment by erudnick-cohen** [comment]
How are you running windows 10? Is it a dual boot on the machine in question, a separate computer, a VM, etc? The errors you're getting are really strange as no one has ever reported an issue like this that I'm aware of and quite a few people have used the exe with windows 10. The runtime environment 14 error occurs because the version of UPR provided only works with java 14 or higher, its detecting a version of what's probably Java 8 that was already present and not the new java you installed I'd guess.

**Comment by c-a0** [comment]
Well... now it works. I didn't do anything differnt, it's just not giving me the error anymore. No clue why.
I'll close the issue. Thanks for trying to help though, I apprecate it.
