### ISSUE TITLE
Crashes after beating Falkner

### ISSUE THREAD

**Issue by RavenTalk** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#6]
After beating Falkner the game crashes.  Used the same randomized ROM and ran it through http://crystal-key-item-randomizer.herokuapp.com/index.html.  That seed passed through Falkner without problem.  RNG Seed on the crashed one was QK8OP7OGX8.  Using Gambatte r717.

**Comment by vicendithas** [comment]
I'll test it and see if the same happens for me. One thing of note is to make sure you are using Crystal Speedchoice 7.1. The latest release of this has not yet been updated for 7.2.

**Comment by RavenTalk** [comment]
Disregard for now.  I just checked and I used the Speedchoice V6.  Got it mixed up with what the web-based randomizer uses.  I'll retest the seed with 7.1.  Don't want you to waste your time.  Thanks for quick response.

**Comment by vicendithas** [comment]
Not a problem. It can be tricky to remember which applications support which speedchoice versions.

**Comment by erudnick-cohen** [comment]
Issue closed on basis of wrong version being used. I really need to get around to implementing a version check in the actual code to catch these situations.
