### ISSUE TITLE
Surf shuffled into waterfall location using ClassicKeyItemRando logic

### ISSUE THREAD

**Issue by RavenTalk** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#8]
Based on spoiler log it looks like surf got shuffled into the waterfall hm location, which is inaccessible without surf.  This was using the ClassicKeyItemRando.yml.  

RNG Seed: JQWBIJX0TO
Solution:
  Basement Key: Cut HM
  Bicycle: Buena Item
  Card Key: Vermillion City Lost Item
  Cut: Sprout Tower Sage Li
  Flash: Super Rod
  Fly: Chuck's Wife
  Fog Badge: Vermillion City Gym Badge
  Glacier Badge: Celadon City Gym Badge
  Hive Badge: Violet City Gym Badge
  Lost Item: Rocket Base Whirlpool
  Machine Part: Dance Theatre
  Pass: Goldenrod City Flower Shop
  Plain Badge: Goldenrod City Gym
  Rising Badge: Cianwood City Gym Badge
  S S Ticket: Hidden Machine Part
  Secret Potion: Silver Wing
  Squirtbottle: Bike
  Storm Badge: Ecruteak City Gym Badge
  Strength: Red Scale Dropped
  Surf: Ice Path Waterfall
  Waterfall: Fishing Guru
  Zephyr Badge: Fuchsia City Gym Badge
Useless Stuff:
  Coin Case: Red Scale
  Goldenrod Tunnel Rocket Attack: GOOD_ROD
  Itemfinder House: SILVER_WING
  Mr. Pokemon's Egg: Clear Bell
  Old Rod: COIN_CASE
  Radio Tower Rockets Part 1: OLD_ROD
  Radio Tower Rockets Part 2: Whirlpool
  Rail Pass: BLUE_CARD
  SS Ticket: ITEMFINDER
  Secret Potion Man: SUPER_ROD
  Strength HM: Mystery Egg

**Comment by erudnick-cohen** [comment]
The waterfall HM (Ice Path) can be reached if you have 7 badges. The pass and squirbottle are available and cut access is also present, so 7 gyms can be accessed (Violet, Azalea, Goldenrod, Ecruteak, Fuchsia, Celadon and Vermilion). This seed should be beatable, is there something preventing you from entering Ice Path with 7 badges?

**Comment by RavenTalk** [comment]
Learn something new every day.  20 seeds of this and only after reading your comment did I realize you can walk through waterfall cave without surf to get to mahogany town.  The seed is beatable.  Apologies for the false alarm and thank you for your quick response as always.
